# Generated by Django 3.1.7 on 2021-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('punchin', models.TimeField(null=True)),
                ('punchout', models.TimeField(null=True)),
                ('spent', models.TimeField(null=True)),
                ('deficiency', models.TimeField(null=True)),
                ('percentile', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('emotion', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
